src/Entity/Institut.php
<?php

namespace App\Entity;

use App\Repository\InstitutRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: InstitutRepository::class)]
class Institut
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $institut_id = null;

    #[ORM\Column(length: 255)]
    private ?string $nomi = null;

    #[ORM\OneToMany(targetEntity: Etudiant::class, mappedBy: 'instit')]
    private Collection $etudiants;

    public function __construct()
    {
        $this->etudiants = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getInstitutId(): ?int
    {
        return $this->institut_id;
    }

    public function setInstitutId(int $institut_id): static
    {
        $this->institut_id = $institut_id;

        return $this;
    }

    public function getNomi(): ?string
    {
        return $this->nomi;
    }

    public function setNomi(string $nomi): static
    {
        $this->nomi = $nomi;

        return $this;
    }

    /**
     * @return Collection<int, Etudiant>
     */
    public function getEtudiants(): Collection
    {
        return $this->etudiants;
    }

    public function addEtudiant(Etudiant $etudiant): static
    {
        if (!$this->etudiants->contains($etudiant)) {
            $this->etudiants->add($etudiant);
            $etudiant->setInstit($this);
        }

        return $this;
    }

    public function removeEtudiant(Etudiant $etudiant): static
    {
        if ($this->etudiants->removeElement($etudiant)) {
            // set the owning side to null (unless already changed)
            if ($etudiant->getInstit() === $this) {
                $etudiant->setInstit(null);
            }
        }

        return $this;
    }
}

src/Form/InstitutType.php
<?php

namespace App\Form;

use App\Entity\Institut;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class InstitutType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('institut_id')
            ->add('nomi')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Institut::class,
        ]);
    }
}

src/Controller/InstitutController.php
<?php

namespace App\Controller;

use App\Entity\Institut;
use App\Form\InstitutType;
use App\Repository\InstitutRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/institut')]
class InstitutController extends AbstractController
{
    #[Route('/', name: 'app_institut_index', methods: ['GET'])]
    public function index(InstitutRepository $institutRepository): Response
    {
        return $this->render('institut/index.html.twig', [
            'instituts' => $institutRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_institut_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $institut = new Institut();
        $form = $this->createForm(InstitutType::class, $institut);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($institut);
            $entityManager->flush();

            return $this->redirectToRoute('app_institut_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('institut/new.html.twig', [
            'institut' => $institut,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_institut_show', methods: ['GET'])]
    public function show(Institut $institut): Response
    {
        return $this->render('institut/show.html.twig', [
            'institut' => $institut,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_institut_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Institut $institut, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(InstitutType::class, $institut);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_institut_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('institut/edit.html.twig', [
            'institut' => $institut,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_institut_delete', methods: ['POST'])]
    public function delete(Request $request, Institut $institut, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$institut->getId(), $request->request->get('_token'))) {
            $entityManager->remove($institut);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_institut_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/institut/_delete_form.html.twig
<form method="post" action="{{ path('app_institut_delete', {'id': institut.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ institut.id) }}">
    <button class="btn">Delete</button>
</form>

templates/institut/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/institut/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Institut{% endblock %}

{% block body %}
    <h1>Edit Institut</h1>

    {{ include('institut/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_institut_index') }}">back to list</a>

    {{ include('institut/_delete_form.html.twig') }}
{% endblock %}

templates/institut/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Institut index{% endblock %}

{% block body %}
    <h1>Institut index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Institut_id</th>
                <th>Nomi</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for institut in instituts %}
            <tr>
                <td>{{ institut.id }}</td>
                <td>{{ institut.institutId }}</td>
                <td>{{ institut.nomi }}</td>
                <td>
                    <a href="{{ path('app_institut_show', {'id': institut.id}) }}">show</a>
                    <a href="{{ path('app_institut_edit', {'id': institut.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_institut_new') }}">Create new</a>
{% endblock %}

templates/institut/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Institut{% endblock %}

{% block body %}
    <h1>Create new Institut</h1>

    {{ include('institut/_form.html.twig') }}

    <a href="{{ path('app_institut_index') }}">back to list</a>
{% endblock %}

templates/institut/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Institut{% endblock %}

{% block body %}
    <h1>Institut</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ institut.id }}</td>
            </tr>
            <tr>
                <th>Institut_id</th>
                <td>{{ institut.institutId }}</td>
            </tr>
            <tr>
                <th>Nomi</th>
                <td>{{ institut.nomi }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_institut_index') }}">back to list</a>

    <a href="{{ path('app_institut_edit', {'id': institut.id}) }}">edit</a>

    {{ include('institut/_delete_form.html.twig') }}
{% endblock %}