src/Entity/Etudiant.php
<?php

namespace App\Entity;

use App\Repository\EtudiantRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EtudiantRepository::class)]
class Etudiant
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $etudiant_id = null;

    #[ORM\Column(length: 255)]
    private ?string $nome = null;

    #[ORM\ManyToOne(inversedBy: 'etudiants')]
    #[ORM\JoinColumn(nullable: false)]
    /**
      * @ORM\ManyToOne(targetEntity= "Institut")
      * @ORM\JoinColumn(name="institut_id", referencedColumnName="id")
      */

    private ?institut $instit = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEtudiantId(): ?int
    {
        return $this->etudiant_id;
    }

    public function setEtudiantId(int $etudiant_id): static
    {
        $this->etudiant_id = $etudiant_id;

        return $this;
    }

    public function getNome(): ?string
    {
        return $this->nome;
    }

    public function setNome(string $nome): static
    {
        $this->nome = $nome;

        return $this;
    }

    public function getInstit(): ?institut
    {
        return $this->instit;
    }

    public function setInstit(?institut $instit): static
    {
        $this->instit = $instit;

        return $this;
    }
}

src/Form/EtudiantType.php
<?php

namespace App\Form;

use App\Entity\Etudiant;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

class EtudiantType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('etudiant_id')
            ->add('nome')
            ->add('institut',EntityType::class,array('class'=>'Institut','choice_label'=>'nomi','choice_value'=>'id') )

        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Etudiant::class,
        ]);
    }
}

src/Controller/EtudiantController.php
<?php

namespace App\Controller;

use App\Entity\Etudiant;
use App\Form\EtudiantType;
use App\Repository\EtudiantRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/etudiant')]
class EtudiantController extends AbstractController
{
    #[Route('/', name: 'app_etudiant_index', methods: ['GET'])]
    public function index(EtudiantRepository $etudiantRepository): Response
    {
        return $this->render('etudiant/index.html.twig', [
            'etudiants' => $etudiantRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_etudiant_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $etudiant = new Etudiant();
        $form = $this->createForm(EtudiantType::class, $etudiant);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($etudiant);
            $entityManager->flush();

            return $this->redirectToRoute('app_etudiant_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('etudiant/new.html.twig', [
            'etudiant' => $etudiant,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_etudiant_show', methods: ['GET'])]
    public function show(Etudiant $etudiant): Response
    {
        return $this->render('etudiant/show.html.twig', [
            'etudiant' => $etudiant,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_etudiant_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Etudiant $etudiant, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(EtudiantType::class, $etudiant);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_etudiant_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('etudiant/edit.html.twig', [
            'etudiant' => $etudiant,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_etudiant_delete', methods: ['POST'])]
    public function delete(Request $request, Etudiant $etudiant, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$etudiant->getId(), $request->request->get('_token'))) {
            $entityManager->remove($etudiant);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_etudiant_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/etudiant/_delete_form.html.twig
<form method="post" action="{{ path('app_etudiant_delete', {'id': etudiant.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ etudiant.id) }}">
    <button class="btn">Delete</button>
</form>

templates/etudiant/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/etudiant/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Etudiant{% endblock %}

{% block body %}
    <h1>Edit Etudiant</h1>

    {{ include('etudiant/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_etudiant_index') }}">back to list</a>

    {{ include('etudiant/_delete_form.html.twig') }}
{% endblock %}

templates/etudiant/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Etudiant index{% endblock %}

{% block body %}
    <h1>Etudiant index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Etudiant_id</th>
                <th>Nome</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for etudiant in etudiants %}
            <tr>
                <td>{{ etudiant.id }}</td>
                <td>{{ etudiant.etudiantId }}</td>
                <td>{{ etudiant.nome }}</td>
                <td>
                    <a href="{{ path('app_etudiant_show', {'id': etudiant.id}) }}">show</a>
                    <a href="{{ path('app_etudiant_edit', {'id': etudiant.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_etudiant_new') }}">Create new</a>
{% endblock %}

templates/etudiant/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Etudiant{% endblock %}

{% block body %}
    <h1>Create new Etudiant</h1>

    {{ include('etudiant/_form.html.twig') }}

    <a href="{{ path('app_etudiant_index') }}">back to list</a>
{% endblock %}

templates/etudiant/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Etudiant{% endblock %}

{% block body %}
    <h1>Etudiant</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ etudiant.id }}</td>
            </tr>
            <tr>
                <th>Etudiant_id</th>
                <td>{{ etudiant.etudiantId }}</td>
            </tr>
            <tr>
                <th>Nome</th>
                <td>{{ etudiant.nome }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_etudiant_index') }}">back to list</a>

    <a href="{{ path('app_etudiant_edit', {'id': etudiant.id}) }}">edit</a>

    {{ include('etudiant/_delete_form.html.twig') }}
{% endblock %}